### PR TITLE
Fix campaignOwner mapping

### PR DESCRIPTION
**Pull request by tobiasbexelius**

### CODE REVIEW

**Review by robinandeer — CHANGES_REQUESTED** [review]
Hmmm, I'm pretty sure we are using this `owner` property at least when getting `redeemedCampaigns` 🤔 or is this separate from that?

That would break our production build. Can we fix this without breaking API changes?

**Comment by tobiasbexelius** [comment]
@robinandeer This is only called by quoteCart

**Comment by robinandeer** [comment]
Okey understood! In that case it's okey to break the API since we don't use it in prod yet

**Review by robinandeer — APPROVED** [review]
If this only affects quote cart API - it looks good!

**Pull request merged**
